defmodule DungeonCasterWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :dungeon_caster

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_dungeon_caster_key",
    signing_salt: "CHKGNVsl",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  socket "/socket", DungeonCasterWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Serve phoenix.js UMD build for non-LiveView pages (e.g. Chromecast receiver)
  plug Plug.Static,
    at: "/assets",
    from: {:phoenix, "priv/static"},
    only: ~w(phoenix.js)

  # Serve vendored JS libraries (qrcode.min.js etc.) at /assets/
  plug Plug.Static,
    at: "/assets",
    from: Path.expand("../../assets/vendor", __DIR__),
    only: ~w(qrcode.min.js)

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :dungeon_caster,
    gzip: not code_reloading?,
    only: DungeonCasterWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Serve campaign map assets from the campaign directory at runtime
  plug DungeonCasterWeb.Plugs.CampaignStatic

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :dungeon_caster
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug DungeonCasterWeb.Router
end
